USE SUSUSHISHI
GO

-- Index1

SELECT * FROM ACCOUNT
WHERE USERNAME = 'christie95'



SELECT * FROM ACCOUNT
SET STATISTICS TIME ON
GO
EXEC getUserIdByAccount 'juan95'
GO
SET STATISTICS TIME OFF
CREATE UNIQUE INDEX IDX_ACCOUNT_USERNAME ON ACCOUNT(USERNAME) 
DROP INDEX ACCOUNT.IDX_ACCOUNT_USERNAME

GO
-- Idx2

CREATE UNIQUE INDEX IDX_CUSTOMER_PHONENUMBER ON CUSTOMER(PHONE_NUMBER)
DROP INDEX CUSTOMER.IDX_CUSTOMER_PHONENUMBER
SELECT * FROM CUSTOMER WHERE PHONE_NUMBER = '910945519'

SET STATISTICS TIME ON
EXEC getInvoiceByPhone @CUSTOMER_PHONE = '910945519'
SET STATISTICS TIME OFF


EXEC createCustomerCardForNew N'TẤN lộc', '012345679', 'loc123@gmail.com', '975748891772841', N'Nam', NULL 


-- IDX3:
CREATE NONCLUSTERED INDEX IX_EMPLOYEE_COVERAGE
ON EMPLOYEE(DEPARTMENT_ID)
INCLUDE (EMPLOYEE_ID, FULL_NAME, DATE_OF_BIRTH, GENDER, SALARY, 
         START_DATE_WORK, TERMINATION_DATE)
DROP INDEX EMPLOYEE.IX_EMPLOYEE_COVERAGE 


SELECT * 
FROM EMPLOYEE E 
JOIN DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE D.BRANCH_ID = 'B010'

EXEC addResource 'B003', 'Hello', 'Nam', '05-12-2004', '1-1-2020', 'D015', '123'

/*
CUSTOMER

EMPLOYEE

ACCOUNT
*/