/*
CREATE DATABASE [SUSUSHISHI_NoIndex]
GO
*/
USE SUSUSHISHI_NoIndex
GO

-- 1.Tạo bảng MEMBERSHIP_CARD
CREATE TABLE MEMBERSHIP_CARD (
    CARD_ID CHAR(7) NOT NULL,
	CARD_TYPE NVARCHAR(15),
    CUSTOMER_ID CHAR(7),
	DATE_ISSUED DATE NOT NULL,
	EMPLOYEE_ID CHAR(7),
	POINTS INT DEFAULT 0,
    CARD_STATUS NVARCHAR(10) ,
	DISCOUNT_AMOUNT INT
)
GO

-- 2. Tạo bảng EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID CHAR(7) NOT NULL,
    FULL_NAME NVARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER NCHAR(3),
    SALARY INT,
    START_DATE_WORK DATE NOT NULL,
	TERMINATION_DATE DATE,
    DEPARTMENT_ID CHAR(4)
)
GO

-- 3. Tạo bảng DEPARTMENT
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID CHAR(4) NOT NULL,
    DEPARTMENT_NAME NVARCHAR(100),
	BRANCH_ID CHAR(4)
)
GO

-- 4. Tạo bảng WORK_HISTORY
CREATE TABLE WORK_HISTORY (
	BRANCH_START_DATE DATE NOT NULL,
	BRANCH_END_DATE DATE,
	EMPLOYEE_ID CHAR(7) NOT NULL,
    BRANCH_ID CHAR(4)
)
GO

-- 5. Tạo bảng RESTAURANT_BRANCH
CREATE TABLE RESTAURANT_BRANCH (
    BRANCH_ID CHAR(4) NOT NULL,
	BRANCH_PHONE VARCHAR(15) NOT NULL,
    BRANCH_NAME NVARCHAR(100) NOT NULL,
	BRANCH_ADDRESS NVARCHAR(255),
	OPEN_TIME TIME,
	CLOSE_TIME TIME,
	CAR_PARK BIT NOT NULL,
	MOTORBIKE_PARK BIT NOT NULL,
	MANAGER_ID CHAR(7),
    AREA_NAME NVARCHAR(50)
)
GO

-- 6. Tạo bảng DISH_AVAILABLE
CREATE TABLE DISH_AVAILABLE (
    BRANCH_ID CHAR(4) NOT NULL,
    DISH_ID CHAR(4) NOT NULL,
    IS_AVAILABLE BIT NOT NULL,
    IS_DELIVERABLE BIT NOT NULL
)
GO

-- 7. Tạo bảng DISH
CREATE TABLE DISH (
    DISH_ID CHAR(4) NOT NULL,
    DISH_NAME NVARCHAR(100),
	CATEGORY_NAME NVARCHAR(100) NOT NULL,
    DISH_PRICE DECIMAL(10,2)
)
GO

-- 8. Tạo bảng ONLINE_ACCESS_HISTORY
CREATE TABLE ONLINE_ACCESS_HISTORY (
    DATE_ACCESSED DATE NOT NULL,
	TIME_ACCESSED TIME NOT NULL,
    CUSTOMER_ID CHAR(7) NOT NULL,
    SESSION_DURATION INT
)
GO

-- 9. Tạo bảng BRANCH_RATING
CREATE TABLE BRANCH_RATING (
    RATING_ID CHAR(7) NOT NULL,
	SERVICE_RATING TINYINT,
	LOCATION_RATING TINYINT,
	PRICE_RATING TINYINT,
	DISH_QUALITY_RATING TINYINT,
	ENVIRONMENT_RATING TINYINT,
	COMMENTS NVARCHAR(200),
    BRANCH_ID CHAR(4),
    RATING_DATE DATETIME,
	INVOICE_ID CHAR(7)
)
GO

-- 10. Tạo bảng INVOICE
CREATE TABLE INVOICE (
    INVOICE_ID CHAR(7) NOT NULL,
    FINAL_AMOUNT INT,
	DISCOUNT_AMOUNT INT,
    ISSUE_DATE DATE,
	ISSUE_TIME TIME,
    ORDER_ID CHAR(7)
)
GO

-- 11. Tạo bảng ORDER_DISH
CREATE TABLE ORDER_DISH (
    ORDER_ID CHAR(7) NOT NULL, 
    DISH_ID CHAR(4) NOT NULL,
    QUANTITY TINYINT
)
GO

-- 12. Tạo bảng DELIVERY_ORDER
CREATE TABLE DELIVERY_ORDER (
    DORDER_ID CHAR(7) NOT NULL,
    TIME_DELIVERY TIME,
	DATE_DELIVERY DATE
) 
GO

-- 13. Tạo bảng OFFLINE_ORDER
CREATE TABLE OFFLINE_ORDER (
    OFORDER_ID CHAR(7) NOT NULL,
	TABLE_NUMBER TINYINT,
    EMPLOYEE_ID CHAR(7),
    BRANCH_ID CHAR(4),
	EMPLYEE_RATING TINYINT
)
GO

-- 14. Tạo bảng ONLINE_ORDER
CREATE TABLE ONLINE_ORDER (
    OORDER_ID CHAR(7) NOT NULL,
    ARRIVAL_DATE DATE,
    ARRIVAL_TIME TIME,
    TABLE_NUMBER TINYINT,
    BRANCH_ID CHAR(4),
    CUSTOMER_QUANTITY TINYINT
)
GO

-- 15. Tạo bảng ORDER
CREATE TABLE ORDER_ (
    ORDER_ID CHAR(7) NOT NULL,
    ORDER_DATE DATE,
    BRANCH_ID CHAR(4),
    CUSTOMER_ID CHAR(7),
    ORDER_TYPE VARCHAR(20),
    ORDER_TIME TIME
)
GO

-- 16. Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER (
    CUSTOMER_ID CHAR(7) NOT NULL,
    FULL_NAME NVARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(50),
    IDENTITY_CARD VARCHAR(20),
    GENDER NCHAR(3)
)
GO

-- 17. Tạo bảng TABLE
CREATE TABLE TABLE_ (
    TABLE_NUM TINYINT NOT NULL,
    BRANCH_ID CHAR(4) NOT NULL,
    TABLE_STATUS NVARCHAR(100),
    SEAT_AVAILABLE INT
)
GO

-- 18. Tạo bảng ACCOUNT
CREATE TABLE ACCOUNT (
    ACCOUNT_ID CHAR(7) NOT NULL,
    USERNAME NVARCHAR(50),
    PASSWORD VARCHAR(255),
    ROLE NVARCHAR(20),
	EMPLOYEE_ID CHAR(7),
    CUSTOMER_ID CHAR(7)
)
GO
